### PR TITLE
Update build.gradle with missing jcenter() repo for buildscript

### PR DESCRIPTION
**Pull request by yedidyak**

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@yedidyak Wasn't the whole point of this fork to remove jcenter?

**Comment by yedidyak** [comment]
> @yedidyak Wasn't the whole point of this fork to remove jcenter?

True, then we need to update the dependencies there as they aren't in any other repo.

**Comment by Inbal-Tish** [comment]
> > @yedidyak Wasn't the whole point of this fork to remove jcenter?
> 
> True, then we need to update the dependencies there as they aren't in any other repo.

I don't understand... I removed jcenter from repositories as well... Where do we need to update the dependencies?

**Comment by yedidyak** [comment]
I;m not sure what happened, but without it it failed to find some dependency locally, i'll try and investigate more.

**Pull request closed without merging**
